/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ISandboxApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Удаление всех позиций
        /// </summary>
        /// <remarks>
        /// Удаление всех позиций клиента
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Empty</returns>
        Empty SandboxClearPost ();

        /// <summary>
        /// Удаление всех позиций
        /// </summary>
        /// <remarks>
        /// Удаление всех позиций клиента
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Empty</returns>
        ApiResponse<Empty> SandboxClearPostWithHttpInfo ();
        /// <summary>
        /// Выставление баланса по валютным позициям
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по валютным позициям</param>
        /// <returns>Empty</returns>
        Empty SandboxCurrenciesBalancePost (SandboxSetCurrencyBalanceRequest body);

        /// <summary>
        /// Выставление баланса по валютным позициям
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по валютным позициям</param>
        /// <returns>ApiResponse of Empty</returns>
        ApiResponse<Empty> SandboxCurrenciesBalancePostWithHttpInfo (SandboxSetCurrencyBalanceRequest body);
        /// <summary>
        /// Выставление баланса по инструментным позициям
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по инструментным позициям</param>
        /// <returns>Empty</returns>
        Empty SandboxPositionsBalancePost (SandboxSetPositionBalanceRequest body);

        /// <summary>
        /// Выставление баланса по инструментным позициям
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по инструментным позициям</param>
        /// <returns>ApiResponse of Empty</returns>
        ApiResponse<Empty> SandboxPositionsBalancePostWithHttpInfo (SandboxSetPositionBalanceRequest body);
        /// <summary>
        /// Регистрация клиента в sandbox
        /// </summary>
        /// <remarks>
        /// Создание валютные позиций для клиента
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Empty</returns>
        Empty SandboxRegisterPost ();

        /// <summary>
        /// Регистрация клиента в sandbox
        /// </summary>
        /// <remarks>
        /// Создание валютные позиций для клиента
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Empty</returns>
        ApiResponse<Empty> SandboxRegisterPostWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Удаление всех позиций
        /// </summary>
        /// <remarks>
        /// Удаление всех позиций клиента
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Empty</returns>
        System.Threading.Tasks.Task<Empty> SandboxClearPostAsync ();

        /// <summary>
        /// Удаление всех позиций
        /// </summary>
        /// <remarks>
        /// Удаление всех позиций клиента
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Empty)</returns>
        System.Threading.Tasks.Task<ApiResponse<Empty>> SandboxClearPostAsyncWithHttpInfo ();
        /// <summary>
        /// Выставление баланса по валютным позициям
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по валютным позициям</param>
        /// <returns>Task of Empty</returns>
        System.Threading.Tasks.Task<Empty> SandboxCurrenciesBalancePostAsync (SandboxSetCurrencyBalanceRequest body);

        /// <summary>
        /// Выставление баланса по валютным позициям
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по валютным позициям</param>
        /// <returns>Task of ApiResponse (Empty)</returns>
        System.Threading.Tasks.Task<ApiResponse<Empty>> SandboxCurrenciesBalancePostAsyncWithHttpInfo (SandboxSetCurrencyBalanceRequest body);
        /// <summary>
        /// Выставление баланса по инструментным позициям
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по инструментным позициям</param>
        /// <returns>Task of Empty</returns>
        System.Threading.Tasks.Task<Empty> SandboxPositionsBalancePostAsync (SandboxSetPositionBalanceRequest body);

        /// <summary>
        /// Выставление баланса по инструментным позициям
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по инструментным позициям</param>
        /// <returns>Task of ApiResponse (Empty)</returns>
        System.Threading.Tasks.Task<ApiResponse<Empty>> SandboxPositionsBalancePostAsyncWithHttpInfo (SandboxSetPositionBalanceRequest body);
        /// <summary>
        /// Регистрация клиента в sandbox
        /// </summary>
        /// <remarks>
        /// Создание валютные позиций для клиента
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Empty</returns>
        System.Threading.Tasks.Task<Empty> SandboxRegisterPostAsync ();

        /// <summary>
        /// Регистрация клиента в sandbox
        /// </summary>
        /// <remarks>
        /// Создание валютные позиций для клиента
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Empty)</returns>
        System.Threading.Tasks.Task<ApiResponse<Empty>> SandboxRegisterPostAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class SandboxApi : ISandboxApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SandboxApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SandboxApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SandboxApi"/> class
        /// </summary>
        /// <returns></returns>
        public SandboxApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SandboxApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SandboxApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Удаление всех позиций Удаление всех позиций клиента
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Empty</returns>
        public Empty SandboxClearPost ()
        {
             ApiResponse<Empty> localVarResponse = SandboxClearPostWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Удаление всех позиций Удаление всех позиций клиента
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Empty</returns>
        public ApiResponse< Empty > SandboxClearPostWithHttpInfo ()
        {

            var localVarPath = "/sandbox/clear";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (sso_auth) required

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SandboxClearPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

        /// <summary>
        /// Удаление всех позиций Удаление всех позиций клиента
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Empty</returns>
        public async System.Threading.Tasks.Task<Empty> SandboxClearPostAsync ()
        {
             ApiResponse<Empty> localVarResponse = await SandboxClearPostAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Удаление всех позиций Удаление всех позиций клиента
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Empty)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Empty>> SandboxClearPostAsyncWithHttpInfo ()
        {

            var localVarPath = "/sandbox/clear";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (sso_auth) required

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SandboxClearPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

        /// <summary>
        /// Выставление баланса по валютным позициям 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по валютным позициям</param>
        /// <returns>Empty</returns>
        public Empty SandboxCurrenciesBalancePost (SandboxSetCurrencyBalanceRequest body)
        {
             ApiResponse<Empty> localVarResponse = SandboxCurrenciesBalancePostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Выставление баланса по валютным позициям 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по валютным позициям</param>
        /// <returns>ApiResponse of Empty</returns>
        public ApiResponse< Empty > SandboxCurrenciesBalancePostWithHttpInfo (SandboxSetCurrencyBalanceRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SandboxApi->SandboxCurrenciesBalancePost");

            var localVarPath = "/sandbox/currencies/balance";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (sso_auth) required

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SandboxCurrenciesBalancePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

        /// <summary>
        /// Выставление баланса по валютным позициям 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по валютным позициям</param>
        /// <returns>Task of Empty</returns>
        public async System.Threading.Tasks.Task<Empty> SandboxCurrenciesBalancePostAsync (SandboxSetCurrencyBalanceRequest body)
        {
             ApiResponse<Empty> localVarResponse = await SandboxCurrenciesBalancePostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Выставление баланса по валютным позициям 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по валютным позициям</param>
        /// <returns>Task of ApiResponse (Empty)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Empty>> SandboxCurrenciesBalancePostAsyncWithHttpInfo (SandboxSetCurrencyBalanceRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SandboxApi->SandboxCurrenciesBalancePost");

            var localVarPath = "/sandbox/currencies/balance";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (sso_auth) required

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SandboxCurrenciesBalancePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

        /// <summary>
        /// Выставление баланса по инструментным позициям 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по инструментным позициям</param>
        /// <returns>Empty</returns>
        public Empty SandboxPositionsBalancePost (SandboxSetPositionBalanceRequest body)
        {
             ApiResponse<Empty> localVarResponse = SandboxPositionsBalancePostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Выставление баланса по инструментным позициям 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по инструментным позициям</param>
        /// <returns>ApiResponse of Empty</returns>
        public ApiResponse< Empty > SandboxPositionsBalancePostWithHttpInfo (SandboxSetPositionBalanceRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SandboxApi->SandboxPositionsBalancePost");

            var localVarPath = "/sandbox/positions/balance";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (sso_auth) required

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SandboxPositionsBalancePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

        /// <summary>
        /// Выставление баланса по инструментным позициям 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по инструментным позициям</param>
        /// <returns>Task of Empty</returns>
        public async System.Threading.Tasks.Task<Empty> SandboxPositionsBalancePostAsync (SandboxSetPositionBalanceRequest body)
        {
             ApiResponse<Empty> localVarResponse = await SandboxPositionsBalancePostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Выставление баланса по инструментным позициям 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Запрос на выставление баланса по инструментным позициям</param>
        /// <returns>Task of ApiResponse (Empty)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Empty>> SandboxPositionsBalancePostAsyncWithHttpInfo (SandboxSetPositionBalanceRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SandboxApi->SandboxPositionsBalancePost");

            var localVarPath = "/sandbox/positions/balance";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (sso_auth) required

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SandboxPositionsBalancePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

        /// <summary>
        /// Регистрация клиента в sandbox Создание валютные позиций для клиента
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Empty</returns>
        public Empty SandboxRegisterPost ()
        {
             ApiResponse<Empty> localVarResponse = SandboxRegisterPostWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Регистрация клиента в sandbox Создание валютные позиций для клиента
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Empty</returns>
        public ApiResponse< Empty > SandboxRegisterPostWithHttpInfo ()
        {

            var localVarPath = "/sandbox/register";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (sso_auth) required

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SandboxRegisterPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

        /// <summary>
        /// Регистрация клиента в sandbox Создание валютные позиций для клиента
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Empty</returns>
        public async System.Threading.Tasks.Task<Empty> SandboxRegisterPostAsync ()
        {
             ApiResponse<Empty> localVarResponse = await SandboxRegisterPostAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Регистрация клиента в sandbox Создание валютные позиций для клиента
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Empty)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Empty>> SandboxRegisterPostAsyncWithHttpInfo ()
        {

            var localVarPath = "/sandbox/register";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (sso_auth) required

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SandboxRegisterPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

    }
}
