/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines InstrumentType
    /// </summary>
        public enum InstrumentType
    {
        /// <summary>
        /// Enum Stock for value: Stock
        /// </summary>
        
        Stock = Stock,
        /// <summary>
        /// Enum Currency for value: Currency
        /// </summary>
        
        Currency = Currency,
        /// <summary>
        /// Enum Bond for value: Bond
        /// </summary>
        
        Bond = Bond,
        /// <summary>
        /// Enum Etf for value: Etf
        /// </summary>
        
        Etf = Etf    }
}
