/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines OperationInterval
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum OperationInterval
    {
        /// <summary>
        /// Enum _1day for value: 1day
        /// </summary>
        [EnumMember(Value = "1day")]
        _1day = 0,
        /// <summary>
        /// Enum _7days for value: 7days
        /// </summary>
        [EnumMember(Value = "7days")]
        _7days = 1,
        /// <summary>
        /// Enum _14days for value: 14days
        /// </summary>
        [EnumMember(Value = "14days")]
        _14days = 2,
        /// <summary>
        /// Enum _30days for value: 30days
        /// </summary>
        [EnumMember(Value = "30days")]
        _30days = 3    }
}
