/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Статус заявки
    /// </summary>
    /// <value>Статус заявки</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum OperationStatus
    {
        /// <summary>
        /// Enum Done for value: Done
        /// </summary>
        [EnumMember(Value = "Done")]
        Done = 0,
        /// <summary>
        /// Enum Decline for value: Decline
        /// </summary>
        [EnumMember(Value = "Decline")]
        Decline = 1,
        /// <summary>
        /// Enum Progress for value: Progress
        /// </summary>
        [EnumMember(Value = "Progress")]
        Progress = 2    }
}
