/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Тип заявки
    /// </summary>
    /// <value>Тип заявки</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum OrderType
    {
        /// <summary>
        /// Enum Limit for value: Limit
        /// </summary>
        [EnumMember(Value = "Limit")]
        Limit = 0,
        /// <summary>
        /// Enum Market for value: Market
        /// </summary>
        [EnumMember(Value = "Market")]
        Market = 1    }
}
