/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrdersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OrdersApiTests
    {
        private OrdersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrdersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrdersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrdersApi
            //Assert.IsInstanceOfType(typeof(OrdersApi), instance, "instance is a OrdersApi");
        }

        /// <summary>
        /// Test OrdersCancelPost
        /// </summary>
        [Test]
        public void OrdersCancelPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orderId = null;
            //Empty body = null;
            //var response = instance.OrdersCancelPost(orderId, body);
            //Assert.IsInstanceOf<Empty> (response, "response is Empty");
        }
        /// <summary>
        /// Test OrdersGet
        /// </summary>
        [Test]
        public void OrdersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.OrdersGet();
            //Assert.IsInstanceOf<OrdersResponse> (response, "response is OrdersResponse");
        }
        /// <summary>
        /// Test OrdersLimitOrderPost
        /// </summary>
        [Test]
        public void OrdersLimitOrderPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LimitOrderRequest body = null;
            //string figi = null;
            //var response = instance.OrdersLimitOrderPost(body, figi);
            //Assert.IsInstanceOf<LimitOrderResponse> (response, "response is LimitOrderResponse");
        }
    }

}
