/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SandboxApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SandboxApiTests
    {
        private SandboxApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SandboxApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SandboxApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SandboxApi
            //Assert.IsInstanceOfType(typeof(SandboxApi), instance, "instance is a SandboxApi");
        }

        /// <summary>
        /// Test SandboxClearPost
        /// </summary>
        [Test]
        public void SandboxClearPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SandboxClearPost();
            //Assert.IsInstanceOf<Empty> (response, "response is Empty");
        }
        /// <summary>
        /// Test SandboxCurrenciesBalancePost
        /// </summary>
        [Test]
        public void SandboxCurrenciesBalancePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SandboxSetCurrencyBalanceRequest body = null;
            //var response = instance.SandboxCurrenciesBalancePost(body);
            //Assert.IsInstanceOf<Empty> (response, "response is Empty");
        }
        /// <summary>
        /// Test SandboxPositionsBalancePost
        /// </summary>
        [Test]
        public void SandboxPositionsBalancePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SandboxSetPositionBalanceRequest body = null;
            //var response = instance.SandboxPositionsBalancePost(body);
            //Assert.IsInstanceOf<Empty> (response, "response is Empty");
        }
        /// <summary>
        /// Test SandboxRegisterPost
        /// </summary>
        [Test]
        public void SandboxRegisterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SandboxRegisterPost();
            //Assert.IsInstanceOf<Empty> (response, "response is Empty");
        }
    }

}
