/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LimitOrderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LimitOrderRequestTests
    {
        // TODO uncomment below to declare an instance variable for LimitOrderRequest
        //private LimitOrderRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LimitOrderRequest
            //instance = new LimitOrderRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LimitOrderRequest
        /// </summary>
        [Test]
        public void LimitOrderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LimitOrderRequest
            //Assert.IsInstanceOfType<LimitOrderRequest> (instance, "variable 'instance' is a LimitOrderRequest");
        }


        /// <summary>
        /// Test the property 'Lots'
        /// </summary>
        [Test]
        public void LotsTest()
        {
            // TODO unit test for the property 'Lots'
        }
        /// <summary>
        /// Test the property 'Operation'
        /// </summary>
        [Test]
        public void OperationTest()
        {
            // TODO unit test for the property 'Operation'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

    }

}
