/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MarketInstrumentList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MarketInstrumentListTests
    {
        // TODO uncomment below to declare an instance variable for MarketInstrumentList
        //private MarketInstrumentList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarketInstrumentList
            //instance = new MarketInstrumentList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarketInstrumentList
        /// </summary>
        [Test]
        public void MarketInstrumentListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MarketInstrumentList
            //Assert.IsInstanceOfType<MarketInstrumentList> (instance, "variable 'instance' is a MarketInstrumentList");
        }


        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Instruments'
        /// </summary>
        [Test]
        public void InstrumentsTest()
        {
            // TODO unit test for the property 'Instruments'
        }

    }

}
