/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MarketInstrument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MarketInstrumentTests
    {
        // TODO uncomment below to declare an instance variable for MarketInstrument
        //private MarketInstrument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarketInstrument
            //instance = new MarketInstrument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarketInstrument
        /// </summary>
        [Test]
        public void MarketInstrumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MarketInstrument
            //Assert.IsInstanceOfType<MarketInstrument> (instance, "variable 'instance' is a MarketInstrument");
        }


        /// <summary>
        /// Test the property 'Figi'
        /// </summary>
        [Test]
        public void FigiTest()
        {
            // TODO unit test for the property 'Figi'
        }
        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'Isin'
        /// </summary>
        [Test]
        public void IsinTest()
        {
            // TODO unit test for the property 'Isin'
        }
        /// <summary>
        /// Test the property 'MinPriceIncrement'
        /// </summary>
        [Test]
        public void MinPriceIncrementTest()
        {
            // TODO unit test for the property 'MinPriceIncrement'
        }
        /// <summary>
        /// Test the property 'Lot'
        /// </summary>
        [Test]
        public void LotTest()
        {
            // TODO unit test for the property 'Lot'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

    }

}
