/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Operation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OperationTests
    {
        // TODO uncomment below to declare an instance variable for Operation
        //private Operation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Operation
            //instance = new Operation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Operation
        /// </summary>
        [Test]
        public void OperationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Operation
            //Assert.IsInstanceOfType<Operation> (instance, "variable 'instance' is a Operation");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Trades'
        /// </summary>
        [Test]
        public void TradesTest()
        {
            // TODO unit test for the property 'Trades'
        }
        /// <summary>
        /// Test the property 'Commission'
        /// </summary>
        [Test]
        public void CommissionTest()
        {
            // TODO unit test for the property 'Commission'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Payment'
        /// </summary>
        [Test]
        public void PaymentTest()
        {
            // TODO unit test for the property 'Payment'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Figi'
        /// </summary>
        [Test]
        public void FigiTest()
        {
            // TODO unit test for the property 'Figi'
        }
        /// <summary>
        /// Test the property 'InstrumentType'
        /// </summary>
        [Test]
        public void InstrumentTypeTest()
        {
            // TODO unit test for the property 'InstrumentType'
        }
        /// <summary>
        /// Test the property 'IsMarginCall'
        /// </summary>
        [Test]
        public void IsMarginCallTest()
        {
            // TODO unit test for the property 'IsMarginCall'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'OperationType'
        /// </summary>
        [Test]
        public void OperationTypeTest()
        {
            // TODO unit test for the property 'OperationType'
        }

    }

}
