/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Order
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderTests
    {
        // TODO uncomment below to declare an instance variable for Order
        //private Order instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Order
            //instance = new Order();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Order
        /// </summary>
        [Test]
        public void OrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Order
            //Assert.IsInstanceOfType<Order> (instance, "variable 'instance' is a Order");
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'Figi'
        /// </summary>
        [Test]
        public void FigiTest()
        {
            // TODO unit test for the property 'Figi'
        }
        /// <summary>
        /// Test the property 'Operation'
        /// </summary>
        [Test]
        public void OperationTest()
        {
            // TODO unit test for the property 'Operation'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'RequestedLots'
        /// </summary>
        [Test]
        public void RequestedLotsTest()
        {
            // TODO unit test for the property 'RequestedLots'
        }
        /// <summary>
        /// Test the property 'ExecutedLots'
        /// </summary>
        [Test]
        public void ExecutedLotsTest()
        {
            // TODO unit test for the property 'ExecutedLots'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

    }

}
