/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PlacedLimitOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlacedLimitOrderTests
    {
        // TODO uncomment below to declare an instance variable for PlacedLimitOrder
        //private PlacedLimitOrder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlacedLimitOrder
            //instance = new PlacedLimitOrder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlacedLimitOrder
        /// </summary>
        [Test]
        public void PlacedLimitOrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PlacedLimitOrder
            //Assert.IsInstanceOfType<PlacedLimitOrder> (instance, "variable 'instance' is a PlacedLimitOrder");
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'Operation'
        /// </summary>
        [Test]
        public void OperationTest()
        {
            // TODO unit test for the property 'Operation'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'RejectReason'
        /// </summary>
        [Test]
        public void RejectReasonTest()
        {
            // TODO unit test for the property 'RejectReason'
        }
        /// <summary>
        /// Test the property 'RequestedLots'
        /// </summary>
        [Test]
        public void RequestedLotsTest()
        {
            // TODO unit test for the property 'RequestedLots'
        }
        /// <summary>
        /// Test the property 'ExecutedLots'
        /// </summary>
        [Test]
        public void ExecutedLotsTest()
        {
            // TODO unit test for the property 'ExecutedLots'
        }
        /// <summary>
        /// Test the property 'Commission'
        /// </summary>
        [Test]
        public void CommissionTest()
        {
            // TODO unit test for the property 'Commission'
        }

    }

}
