/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PortfolioPosition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PortfolioPositionTests
    {
        // TODO uncomment below to declare an instance variable for PortfolioPosition
        //private PortfolioPosition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PortfolioPosition
            //instance = new PortfolioPosition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PortfolioPosition
        /// </summary>
        [Test]
        public void PortfolioPositionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PortfolioPosition
            //Assert.IsInstanceOfType<PortfolioPosition> (instance, "variable 'instance' is a PortfolioPosition");
        }


        /// <summary>
        /// Test the property 'Figi'
        /// </summary>
        [Test]
        public void FigiTest()
        {
            // TODO unit test for the property 'Figi'
        }
        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'Isin'
        /// </summary>
        [Test]
        public void IsinTest()
        {
            // TODO unit test for the property 'Isin'
        }
        /// <summary>
        /// Test the property 'InstrumentType'
        /// </summary>
        [Test]
        public void InstrumentTypeTest()
        {
            // TODO unit test for the property 'InstrumentType'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Test]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }
        /// <summary>
        /// Test the property 'ExpectedYield'
        /// </summary>
        [Test]
        public void ExpectedYieldTest()
        {
            // TODO unit test for the property 'ExpectedYield'
        }
        /// <summary>
        /// Test the property 'Lots'
        /// </summary>
        [Test]
        public void LotsTest()
        {
            // TODO unit test for the property 'Lots'
        }

    }

}
