/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Portfolio
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PortfolioTests
    {
        // TODO uncomment below to declare an instance variable for Portfolio
        //private Portfolio instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Portfolio
            //instance = new Portfolio();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Portfolio
        /// </summary>
        [Test]
        public void PortfolioInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Portfolio
            //Assert.IsInstanceOfType<Portfolio> (instance, "variable 'instance' is a Portfolio");
        }


        /// <summary>
        /// Test the property 'Positions'
        /// </summary>
        [Test]
        public void PositionsTest()
        {
            // TODO unit test for the property 'Positions'
        }

    }

}
