/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SandboxSetCurrencyBalanceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SandboxSetCurrencyBalanceRequestTests
    {
        // TODO uncomment below to declare an instance variable for SandboxSetCurrencyBalanceRequest
        //private SandboxSetCurrencyBalanceRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SandboxSetCurrencyBalanceRequest
            //instance = new SandboxSetCurrencyBalanceRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SandboxSetCurrencyBalanceRequest
        /// </summary>
        [Test]
        public void SandboxSetCurrencyBalanceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SandboxSetCurrencyBalanceRequest
            //Assert.IsInstanceOfType<SandboxSetCurrencyBalanceRequest> (instance, "variable 'instance' is a SandboxSetCurrencyBalanceRequest");
        }


        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }

    }

}
