/* 
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SandboxCurrency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SandboxCurrencyTests
    {
        // TODO uncomment below to declare an instance variable for SandboxCurrency
        //private SandboxCurrency instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SandboxCurrency
            //instance = new SandboxCurrency();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SandboxCurrency
        /// </summary>
        [Test]
        public void SandboxCurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SandboxCurrency
            //Assert.IsInstanceOfType<SandboxCurrency> (instance, "variable 'instance' is a SandboxCurrency");
        }



    }

}
